### ISSUE TITLE
Split problem_data.json

### ISSUE THREAD

**Issue by siddhantdev** [labs-asterisk/oichecklist#1]
The problem_data.json file is very big. It's hard to edit it. Wouldn't it be easier if the problems were split across files? Each olympiad could have a folder and each year it's own separate file.

**Comment by knightron0** [comment]
Makes total sense – our original plan was that as well. For now, I've created folders for each olympiad containing files for each year and a [corresponding script](https://github.com/labs-asterisk/oichecklist/tree/main/src/data/combine.py) to combine that data into the original [problem_data.json](https://github.com/labs-asterisk/oichecklist/blob/main/src/data/problem_data.json). Instructions have been added to the README as well. We'll soon eliminate the requirement of running the script and make the webapp pull from the folders directly.

Hope this helps!
